version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - krns
  assignees:
  - pehbehbeh
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - krns
  assignees:
  - pehbehbeh
