name: Test, build and push stable image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run tests
        run: docker-compose -f docker-compose.test.yml run test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta builder
        id: metabuilder
        uses: docker/metadata-action@v4
        with:
          images: |
            sourceboat/docker-phoenix
          flavour: |
            latest=false
          tags: |
            type=semver,pattern=latest-builder
            type=semver,pattern={{version}}-builder
            type=semver,pattern={{major}}.{{minor}}-builder
            type=semver,pattern={{major}}-builder
      -
        name: Docker meta runtime
        id: metaruntime
        uses: docker/metadata-action@v4
        with:
          images: |
            sourceboat/docker-phoenix
          flavour: |
            latest=false
          tags: |
            type=semver,pattern=latest-runtime
            type=semver,pattern={{version}}-runtime
            type=semver,pattern={{major}}.{{minor}}-runtime
            type=semver,pattern={{major}}-runtime
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push builder
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          target: builder
          tags: ${{ steps.metabuilder.outputs.tags }}
      -
        name: Build and push runtime
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          target: runtime
          tags: ${{ steps.metaruntime.outputs.tags }}
